#!/usr/bin/env php
<?php

/**
 * @version     1.0.0-dev
 * @package     FrameX (FX) CLI Plugin
 * @link        https://localzet.gitbook.io
 * 
 * @author      localzet <creator@localzet.ru>
 * 
 * @copyright   Copyright (c) 2018-2020 Zorin Projects 
 * @copyright   Copyright (c) 2020-2022 NONA Team
 * 
 * @license     https://www.localzet.ru/license GNU GPLv3 License
 */

use localzet\FrameX\Config;
use localzet\CLI\Command;

require_once __DIR__ . '/vendor/autoload.php';

if (!in_array($argv[1] ?? '', ['start', 'restart', 'stop', 'status', 'reload', 'connections'])) {
    require_once __DIR__ . '/support/bootstrap.php';
} else {
    Config::reload(config_path(), ['route', 'container']);
}

$cli = new Command();
$cli->setName('localzet cli');
$cli->installInternalCommands();
if (is_dir($command_path = app_path() . '/command')) {
    $cli->installCommands($command_path);
}

foreach (config('plugin', []) as $firm => $projects) {
    foreach ($projects as $name => $project) {
        foreach ($project['command'] ?? [] as $command) {
            $cli->add(new $command);
        }
    }
}

$cli->run();
